"""Files that must meet the strict engineering standard.

Kept in one place so the naming test, CI and humans agree on the scope.
"""

STRICT_FILES: tuple[str, ...] = (
    "ucsa/models/recurrent.py",
    "ucsa/models/graph.py",
    "ucsa/models/curation.py",
    "ucsa/arithmetic.py",
    "ucsa/dryrun.py",
    "ucsa/utils/precision.py",
    "ucsa/training/compression.py",
    "ucsa/training/diagnostics.py",
    "ucsa/training/engine.py",
    "ucsa/training/shards.py",
    "ucsa/training/eval_harness.py",
    "ucsa/training/tuning.py",
    "ucsa/training/prefix.py",
    "ucsa/training/reference.py",
    "scripts/train_r.py",
    "scripts/train.py",
    "scripts/eval.py",
    "scripts/prepare_data.py",
    "scripts/small_config.py",
    "scripts/tune.py",
    "scripts/ablate.py",
    "scripts/dry_run.py",
    "scripts/compress.py",
    "scripts/profile_r.py",
    "tests/strict_files.py",
    "tests/test_naming_policy.py",
    "tests/test_recurrent.py",
    "tests/test_graph.py",
    "tests/test_curation.py",
    "tests/test_arithmetic.py",
    "tests/test_dryrun.py",
    "tests/test_precision.py",
    "tests/test_single_precision.py",
    "tests/test_compression.py",
    "tests/test_diagnostics.py",
    "tests/test_engine.py",
    "tests/test_tuning.py",
    "tests/test_prefix_protocol.py",
    "tests/test_reference.py",
    "tests/test_shards.py",
    "tests/test_eval_harness.py",
)
