import json
import sys

sys.path.insert(0, "scripts")
import report  # noqa: E402


def test_every_section_says_so_when_its_artifact_is_missing(tmp_path):
    text = report.build(str(tmp_path), str(tmp_path / "l"), str(tmp_path / "a"))
    assert text.count("_Not run:") == 9
    assert "Generated by `scripts/report.py`" in text


def test_missing_sections_never_contain_placeholder_numbers(tmp_path):
    text = report.build(str(tmp_path), str(tmp_path), str(tmp_path))
    assert "TODO" not in text
    assert "XX" not in text


def test_compression_table_reports_the_verified_flag_and_anchors():
    out = report.section_compression(
        {
            "tokens": 100,
            "raw_bytes": 400,
            "compressed_bytes": 80,
            "ucsa_bits_per_byte": 1.6,
            "anchors_bits_per_byte": {"zlib": 3.2, "lzma": 3.5},
            "lossless_round_trip": True,
        }
    )
    assert "verified lossless" in out
    assert "| 1.600 |" in out
    assert "3.200" in out


def test_a_failed_round_trip_is_shown_loudly():
    out = report.section_compression(
        {
            "tokens": 1,
            "raw_bytes": 1,
            "compressed_bytes": 1,
            "ucsa_bits_per_byte": 1.0,
            "anchors_bits_per_byte": {"zlib": 1.0, "lzma": 1.0},
            "lossless_round_trip": False,
        }
    )
    assert "FAILED" in out


def test_benchmark_table_lists_published_models_beside_ours():
    rows = [
        {
            "task": "piqa",
            "metric": "acc",
            "ours": 55.0,
            "stderr": 1.2,
            "n": 1838,
            "chance": 50.0,
            "Mamba-130M": 64.5,
        }
    ]
    out = report.section_benchmarks({"reference_comparison": rows})
    assert "Mamba-130M" in out
    assert "55.0 ± 1.2" in out


def test_setup_section_derives_tokens_from_the_config(tmp_path):
    record = {
        "model_config": {
            "hidden": 256,
            "layers": 6,
            "heads": 4,
            "chunk_size": 128,
            "window": None,
            "banks": [["working", 16], ["long_term", 8]],
        },
        "train_config": {
            "steps": 100,
            "batch_size": 8,
            "seq_len": 1024,
            "seed": 42,
        },
        "params": 1_000_000,
        "elapsed_seconds": 3600,
        "final": {"ppl_last64": 123.4, "bpb_last64": 1.5},
    }
    out = report.section_training(record)
    assert "1,000,000" in out
    assert "1M tokens" in out or "1M" in out
    assert "window 128" in out  # None resolves to one chunk
    assert "1.00 h" in out


def test_included_tables_are_passed_through_verbatim(tmp_path):
    (tmp_path / "summary.md").write_text("| a | b |\n|---|---|\n| 1 | 2 |\n")
    out = report.section_file(str(tmp_path / "summary.md"), "x")
    assert out.startswith("| a | b |")
    p = tmp_path / "probe.json"
    p.write_text(json.dumps({"profiles": {}, "rate_distortion": []}))
    assert "state slots read" in report.section_probe(report.load(str(p)))


def ladder_files(folder, arm, losses):
    for steps, loss in zip((150, 300, 600, 1200), losses, strict=True):
        (folder / f"{arm}@{steps}.json").write_text(
            json.dumps(
                {"train_config": {"steps": steps}, "window_nll": [loss] * 3}
            )
        )


def test_the_curve_lists_every_evaluation_with_bits_per_byte():
    record = {
        "history": [
            {"step": 100, "loss": 8.0},
            {"step": 1000, "ppl_all": 247.7, "bpb_all": 1.737},
            {"step": 2000, "ppl_all": 165.5, "bpb_all": 1.610},
        ]
    }
    out = report.section_curve(record)
    assert "| 1000 | 247.7 | 1.737 |" in out
    assert "| 2000 | 165.5 | 1.610 |" in out
    assert "100 |" not in out  # training-loss rows are not evaluations


def test_a_forecast_that_misses_is_reported_as_a_miss(tmp_path):
    import numpy as np

    steps = np.array([150, 300, 600, 1200.0])
    ladder_files(tmp_path, "arm", 2.0 + 20.0 * steps**-0.45)
    record = {
        "train_config": {"steps": 12000},
        "final": {"ppl_all": float(np.exp(9.0))},  # far worse than forecast
    }
    out = report.section_forecast_check([str(tmp_path)], "arm", record, 0.0145)
    assert "OUTSIDE" in out
    assert "optimistic" in out


def test_a_forecast_that_hits_is_reported_as_a_hit(tmp_path):
    import numpy as np

    steps = np.array([150, 300, 600, 1200.0])
    truth = lambda t: 2.0 + 20.0 * t**-0.45  # noqa: E731
    ladder_files(tmp_path, "arm", truth(steps))
    record = {
        "train_config": {"steps": 12000},
        "final": {"ppl_all": float(np.exp(truth(12000.0)))},
    }
    out = report.section_forecast_check([str(tmp_path)], "arm", record, 0.0145)
    assert "inside" in out


def test_the_forecast_check_says_not_run_without_a_record(tmp_path):
    ladder_files(tmp_path, "arm", [5.0, 4.5, 4.0, 3.5])
    assert "_Not run:" in report.section_forecast_check(
        [str(tmp_path)], "arm", None, 0.0145
    )


def test_control_gap_inside_noise_is_not_called_a_win():
    final = {"ppl_all": 82.33, "bpb_all": 1.39}
    control = {"final": {"ppl_all": 81.89, "bpb_all": 1.388}}
    text = report.section_control({"final": final}, control, 0.0145)
    assert "within run-to-run noise" in text


def test_control_gap_beyond_noise_names_the_winner():
    state = {"final": {"ppl_all": 70.0}}
    control = {"final": {"ppl_all": 82.0}}
    assert "state is better" in report.section_control(state, control, 0.0145)
    assert "state is worse" in report.section_control(control, state, 0.0145)
