import json
import sys

sys.path.insert(0, "scripts")
import report  # noqa: E402


def test_every_section_says_so_when_its_artifact_is_missing(tmp_path):
    text = report.build(str(tmp_path), str(tmp_path / "l"), str(tmp_path / "a"))
    assert text.count("_Not run:") == 6
    assert "Generated by `scripts/report.py`" in text


def test_missing_sections_never_contain_placeholder_numbers(tmp_path):
    text = report.build(str(tmp_path), str(tmp_path), str(tmp_path))
    assert "TODO" not in text
    assert "XX" not in text


def test_compression_table_reports_the_verified_flag_and_anchors():
    out = report.section_compression(
        {
            "tokens": 100,
            "raw_bytes": 400,
            "compressed_bytes": 80,
            "ucsa_bits_per_byte": 1.6,
            "anchors_bits_per_byte": {"zlib": 3.2, "lzma": 3.5},
            "lossless_round_trip": True,
        }
    )
    assert "verified lossless" in out
    assert "| 1.600 |" in out
    assert "3.200" in out


def test_a_failed_round_trip_is_shown_loudly():
    out = report.section_compression(
        {
            "tokens": 1,
            "raw_bytes": 1,
            "compressed_bytes": 1,
            "ucsa_bits_per_byte": 1.0,
            "anchors_bits_per_byte": {"zlib": 1.0, "lzma": 1.0},
            "lossless_round_trip": False,
        }
    )
    assert "FAILED" in out


def test_benchmark_table_lists_published_models_beside_ours():
    rows = [
        {
            "task": "piqa",
            "metric": "acc",
            "ours": 55.0,
            "stderr": 1.2,
            "n": 1838,
            "chance": 50.0,
            "Mamba-130M": 64.5,
        }
    ]
    out = report.section_benchmarks({"reference_comparison": rows})
    assert "Mamba-130M" in out
    assert "55.0 ± 1.2" in out


def test_setup_section_derives_tokens_from_the_config(tmp_path):
    record = {
        "model_config": {
            "hidden": 256,
            "layers": 6,
            "heads": 4,
            "chunk_size": 128,
            "window": None,
            "banks": [["working", 16], ["long_term", 8]],
        },
        "train_config": {
            "steps": 100,
            "batch_size": 8,
            "seq_len": 1024,
            "seed": 42,
        },
        "params": 1_000_000,
        "elapsed_seconds": 3600,
        "final": {"ppl_last64": 123.4, "bpb_last64": 1.5},
    }
    out = report.section_training(record)
    assert "1,000,000" in out
    assert "1M tokens" in out or "1M" in out
    assert "window 128" in out  # None resolves to one chunk
    assert "1.00 h" in out


def test_included_tables_are_passed_through_verbatim(tmp_path):
    (tmp_path / "summary.md").write_text("| a | b |\n|---|---|\n| 1 | 2 |\n")
    out = report.section_file(str(tmp_path / "summary.md"), "x")
    assert out.startswith("| a | b |")
    p = tmp_path / "probe.json"
    p.write_text(json.dumps({"profiles": {}, "rate_distortion": []}))
    assert "state slots read" in report.section_probe(report.load(str(p)))
