import { PAPER_ROWS, SITE_CONFIG } from '../lib/content';

export function Research() {
  return (
    <section className="section section--alt" id="research">
      <div className="container">
        <div className="section__head section__head--start reveal is-in">
          <span className="section__eyebrow eyebrow">research</span>
          <h2 className="section__title">
            A research companion, not a hidden appendix.
          </h2>
          <p className="section__lede">
            The paper draft, the evaluation tables, the experiment framing, and
            the reproducibility notes live here — at the same level as the code.
          </p>
        </div>

        <div className="paper">
          <div className="paper__copy reveal is-in">
            <p>
              The working paper draft ({' '}
              <a href={SITE_CONFIG.paperUrl} target="_blank" rel="noreferrer noopener">
                paper/PAPER.md
              </a>
              ) targets ICML / NeurIPS and records exactly what the system
              measures, what is in the repo, and what remains to run at
              paper-grade scale. The matched-compute protocol is the spine:
              every UCSA result is paired with a vanilla-Transformer baseline of
              identical parameter count, dataset, and step budget.
            </p>
            <p className="paper__pull">
              “The contribution is the design — a state-centric inductive bias —
              and the protocol that can say which is which. The matched-compute
              baseline is what makes that claim falsifiable.”
            </p>
            <p>
              The headline result for Phase 11 (endogenous origination) is a{' '}
              <em>negative result</em> at the 65M-on-fineweb scale: the
              matched-compute perplexity gap is real but inside one pooled seed
              sd. The paper says so. The matched-compute protocol is what lets
              it say so.
            </p>
            <p>
              A reproduction recipe, hyperparameter appendix, and PCS
              retention-score derivation live in the paper’s appendices. Every
              table reads from <code>runs/*.json</code> so the numbers can be
              regenerated by anyone who can run the scripts.
            </p>
            <div className="paper__ctas">
              <a
                className="btn btn--primary"
                href={SITE_CONFIG.paperUrl}
                target="_blank"
                rel="noreferrer noopener"
              >
                Read the paper →
              </a>
              <a
                className="btn btn--ghost"
                href={SITE_CONFIG.paperTablesUrl}
                target="_blank"
                rel="noreferrer noopener"
              >
                See the tables
              </a>
            </div>
          </div>

          <div className="reveal is-in">
            <div className="paper__table">
              <div className="paper__table-head">
                <span className="paper__table-title">
                  table 1 — matched compute (illustrative)
                </span>
                <span className="paper__table-tag">runs/ucsa-full-seed42.json</span>
              </div>
              <table>
                <thead>
                  <tr>
                    <th>Configuration</th>
                    <th>Params</th>
                    <th>Val PPL</th>
                    <th>Δ vs baseline</th>
                  </tr>
                </thead>
                <tbody>
                  {PAPER_ROWS.map((r) => (
                    <tr key={r.name}>
                      <td>
                        <code>{r.name}</code>
                      </td>
                      <td className="paper__table--num">{r.params}</td>
                      <td className="paper__table--num">{r.ppl}</td>
                      <td>{r.delta}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="paper__note">
              Numbers above are illustrative placeholders. The live table is
              regenerated from <code>runs/*.json</code> by{' '}
              <a
                href={SITE_CONFIG.paperTablesUrl}
                target="_blank"
                rel="noreferrer noopener"
              >
                paper/TABLES.md
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}